"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import type {
  CoverageAnalysis,
  StageRefinements,
  RefinementItem,
  ProcessIteration,
} from "@reconnect/database";
import { useAIGenerationStore, IDLE_OP } from "@/stores/ai-generation-store";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import {
  Sparkle,
  CircleNotch,
  Lightning,
  ArrowsClockwise,
  Warning,
  Info,
  Wrench,
  ClockCounterClockwise,
} from "@phosphor-icons/react";
import { toast } from "sonner";
import { AIDisclaimer } from "@/components/ai/ai-disclaimer";
import type { StageData } from "./process-page-client";

interface RecommendationsPanelProps {
  playbookId: string;
  role: string;
  level: string;
  coverageAnalysis: CoverageAnalysis;
  stages: StageData[];
  initialRefinements: StageRefinements | null;
  onRefinementsChange: (refinements: StageRefinements) => void;
  onApply: (selectedItems: RefinementItem[], allRefinements: StageRefinements, userPrompt: string) => void;
  onRestore?: (entry: ProcessIteration) => void;
  applyInProgress: boolean;
  /** Persisted iteration history — survives refinement clears after apply */
  iterationHistory?: ProcessIteration[];
}

const TYPE_CONFIG = {
  gap_fix: { label: "Gap Fix", color: "border-red-200 bg-red-50 text-red-700", icon: Warning },
  redundancy_fix: { label: "Redundancy", color: "border-blue-200 bg-blue-50 text-blue-700", icon: ArrowsClockwise },
  improvement: { label: "Improvement", color: "border-emerald-200 bg-emerald-50 text-emerald-700", icon: Lightning },
};

const PRIORITY_ORDER = ["critical", "important", "suggested"] as const;

const PRIORITY_LABELS: Record<string, string> = {
  critical: "Critical",
  important: "Important",
  suggested: "Suggested",
};

export function RecommendationsPanel({
  playbookId,
  role,
  level,
  coverageAnalysis,
  stages,
  initialRefinements,
  onRefinementsChange,
  onApply,
  onRestore,
  applyInProgress,
  iterationHistory = [],
}: RecommendationsPanelProps) {
  const [refinements, setRefinements] = useState<StageRefinements | null>(initialRefinements);
  const [userPrompt, setUserPrompt] = useState(initialRefinements?.user_prompt ?? "");
  const saveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const hasAutoGenerated = useRef(false);
  const lastGenerateHashRef = useRef<string | null>(null);

  const genOpKey = `refinements-${playbookId}`;
  const { status: genStatus } = useAIGenerationStore(
    (s) => s.operations[genOpKey] ?? IDLE_OP,
  );
  const isGenerating = genStatus === "loading";

  const selectedCount = refinements?.items.filter((i) => i.selected).length ?? 0;

  // Sync refinements with parent (apply flow clears and restores them)
  useEffect(() => {
    setRefinements(initialRefinements);
    if (initialRefinements) {
      setUserPrompt(initialRefinements.user_prompt ?? "");
    }
  }, [initialRefinements]);

  // Subscribe to store changes (generate only)
  const handleStoreChange = useCallback(
    (op: { status: string; result: unknown; error: string | null }) => {
      if (op.status === "success" && op.result) {
        const data = op.result as StageRefinements;
        setRefinements(data);
        onRefinementsChange(data);
        useAIGenerationStore.getState().clearOperation(genOpKey);
      }
      if (op.status === "error" && op.error) {
        toast.error(op.error);
        useAIGenerationStore.getState().clearOperation(genOpKey);
      }
    },
    [genOpKey, onRefinementsChange],
  );

  useEffect(() => {
    return useAIGenerationStore.subscribe((state, prevState) => {
      const op = state.operations[genOpKey];
      const prevOp = prevState.operations[genOpKey];
      if (op && op !== prevOp) {
        handleStoreChange(op);
      }
    });
  }, [genOpKey, handleStoreChange]);

  // Auto-generate on mount if no refinements exist
  useEffect(() => {
    if (!refinements && !hasAutoGenerated.current && !isGenerating) {
      const storeOp = useAIGenerationStore.getState().operations[genOpKey];
      if (storeOp?.status === "loading") return;
      hasAutoGenerated.current = true;
      handleGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Cleanup debounce timer on unmount / tab switch
  useEffect(() => {
    return () => {
      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
    };
  }, []);

  function handleGenerate() {
    const currentOp = useAIGenerationStore.getState().operations[genOpKey];
    if (currentOp?.status === "loading") return;

    // Skip if identical input and refinements already exist
    const inputHash = `${coverageAnalysis.overall_coverage_score}|${coverageAnalysis.gaps.length}|${stages.length}|${userPrompt}`;
    if (inputHash === lastGenerateHashRef.current && refinements) {
      toast.info("No changes since last generation");
      return;
    }
    lastGenerateHashRef.current = inputHash;

    useAIGenerationStore.getState().startOperation(genOpKey, async () => {
      const res = await fetch("/api/ai/generate-refinements", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          role,
          level,
          coverage_analysis: {
            gaps: coverageAnalysis.gaps,
            redundancies: coverageAnalysis.redundancies,
            recommendations: coverageAnalysis.recommendations,
            requirements_covered: coverageAnalysis.requirements_covered.map((rc) => ({
              requirement: rc.requirement,
              coverage_strength: rc.coverage_strength,
            })),
            overall_coverage_score: coverageAnalysis.overall_coverage_score,
          },
          stages: stages.map((s) => ({
            name: s.name,
            type: s.type,
            focus_areas: (s.focus_areas ?? []).map((fa) => ({
              name: fa.name,
              description: fa.description,
            })),
          })),
          user_prompt: userPrompt || undefined,
        }),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || "Failed to generate recommendations");
      }

      const { data } = await res.json();

      const enriched: StageRefinements = {
        items: data.items.map((item: { title: string; rationale: string; type: RefinementItem["type"]; priority: RefinementItem["priority"]; source_detail?: string; change_summary: string }, i: number) => ({
          ...item,
          id: `ref-${i}`,
          selected: item.priority === "critical" || item.priority === "important",
        })),
        user_prompt: userPrompt,
        generated_at: new Date().toISOString(),
        source_coverage_score: coverageAnalysis.overall_coverage_score,
        disclaimer: data.disclaimer,
      };

      await persistRefinements(enriched);
      return enriched;
    });
  }

  async function persistRefinements(data: StageRefinements) {
    // Always merge iteration history so it survives regeneration
    const payload = iterationHistory.length > 0 ? { ...data, history: iterationHistory } : data;
    const saveRes = await fetch(`/api/playbooks/${playbookId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ stage_refinements: payload }),
    });
    if (!saveRes.ok) {
      console.error("[recommendations] Auto-save failed:", await saveRes.text().catch(() => ""));
      toast.warning("Auto-save failed — your changes may not persist");
    }
  }

  function handleToggleItem(id: string) {
    if (!refinements) return;
    const updated: StageRefinements = {
      ...refinements,
      items: refinements.items.map((item) =>
        item.id === id ? { ...item, selected: !item.selected } : item,
      ),
    };
    setRefinements(updated);
    onRefinementsChange(updated);
    debouncedSave(updated);
  }

  function handlePromptChange(value: string) {
    setUserPrompt(value);
    if (refinements) {
      const updated = { ...refinements, user_prompt: value };
      setRefinements(updated);
      debouncedSave(updated);
    }
  }

  function debouncedSave(data: StageRefinements) {
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
    saveTimerRef.current = setTimeout(() => {
      persistRefinements(data);
    }, 500);
  }

  function handleApplyClick() {
    if (!refinements || selectedCount === 0) return;
    // Cancel any pending debounced save — apply flow persists its own state
    if (saveTimerRef.current) {
      clearTimeout(saveTimerRef.current);
      saveTimerRef.current = null;
    }
    const selected = refinements.items.filter((i) => i.selected);
    onApply(selected, refinements, userPrompt);
  }

  // ── Empty state — generating ──
  if (!refinements && isGenerating) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-border/60 py-16">
        <CircleNotch size={24} weight="bold" className="animate-spin text-muted-foreground/60" />
        <p className="mt-3 text-[14px] text-muted-foreground">
          Analyzing your coverage and generating recommendations...
        </p>
      </div>
    );
  }

  // ── Empty state — no refinements ──
  if (!refinements) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-border/60 py-16">
        <Wrench size={24} weight="duotone" className="text-muted-foreground/40" />
        <p className="mt-3 text-[14px] text-muted-foreground">
          Generate actionable recommendations from your coverage analysis
        </p>
        <Button className="mt-4" onClick={handleGenerate} disabled={isGenerating}>
          <Sparkle size={16} weight="duotone" className="mr-2" />
          Generate Recommendations
        </Button>
      </div>
    );
  }

  // ── Main recommendations list ──
  const grouped = PRIORITY_ORDER.map((priority) => ({
    priority,
    label: PRIORITY_LABELS[priority],
    items: refinements.items.filter((i) => i.priority === priority),
  })).filter((g) => g.items.length > 0);

  const history: ProcessIteration[] = refinements.history ?? iterationHistory;

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <span className="rounded-md border border-border/60 bg-muted/50 px-2.5 py-1 text-[12px] font-medium tabular-nums text-muted-foreground">
            Source: {refinements.source_coverage_score}% coverage
          </span>
          {refinements.items.length > 0 && (
            <span className="text-[12px] text-muted-foreground">
              {refinements.items.length} recommendation{refinements.items.length !== 1 ? "s" : ""}
            </span>
          )}
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={handleGenerate}
          disabled={isGenerating || applyInProgress}
          aria-label="Regenerate recommendations"
        >
          {isGenerating ? (
            <CircleNotch size={16} weight="bold" className="animate-spin" />
          ) : (
            <ArrowsClockwise size={16} weight="duotone" />
          )}
        </Button>
      </div>

      {/* User prompt */}
      <div className="rounded-xl border border-border/40 bg-card p-5 shadow-sm">
        <label className="mb-2 block text-[13px] font-medium text-muted-foreground">
          Additional guidance (optional)
        </label>
        <Textarea
          placeholder="e.g., Focus on technical depth, add a culture fit round, prioritize leadership assessment..."
          value={userPrompt}
          onChange={(e) => handlePromptChange(e.target.value)}
          className="min-h-[60px] resize-none text-[13px]"
          maxLength={500}
          disabled={applyInProgress}
        />
      </div>

      {/* Grouped items */}
      {grouped.map((group) => (
        <div key={group.priority} className="space-y-2">
          <h3 className="text-[13px] font-semibold tracking-tight text-muted-foreground uppercase">
            {group.label}
          </h3>
          <div className="space-y-2">
            {group.items.map((item) => {
              const typeConfig = TYPE_CONFIG[item.type];
              const TypeIcon = typeConfig.icon;
              return (
                <div
                  key={item.id}
                  className="group rounded-xl border border-border/40 bg-card p-5 shadow-sm transition-colors hover:border-border/60"
                >
                  <div className="flex items-start gap-3">
                    <Checkbox
                      checked={item.selected}
                      onCheckedChange={() => handleToggleItem(item.id)}
                      className="mt-0.5"
                      disabled={applyInProgress}
                    />
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <span
                          className={`inline-flex items-center gap-1 rounded-md border px-1.5 py-0.5 text-[11px] font-medium ${typeConfig.color}`}
                        >
                          <TypeIcon size={12} weight="duotone" />
                          {typeConfig.label}
                        </span>
                        <span className="text-[14px] font-medium text-foreground">
                          {item.title}
                        </span>
                      </div>
                      <p className="mt-1.5 text-[13px] leading-relaxed text-muted-foreground">
                        {item.rationale}
                      </p>
                      <p className="mt-1 text-[12px] italic text-muted-foreground/70">
                        {item.change_summary}
                      </p>
                      {item.source_detail && (
                        <p className="mt-1 flex items-center gap-1 text-[11px] text-muted-foreground/60">
                          <Info size={12} />
                          {item.source_detail}
                        </p>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      ))}

      {/* Action bar */}
      <div className="flex items-center justify-between rounded-xl border border-border/40 bg-card px-5 py-4 shadow-sm">
        <span className="text-[13px] text-muted-foreground">
          {selectedCount} of {refinements.items.length} selected
        </span>
        <Button
          onClick={handleApplyClick}
          disabled={selectedCount === 0 || applyInProgress || isGenerating}
        >
          <Sparkle size={16} weight="duotone" className="mr-2" />
          Apply Selected ({selectedCount})
        </Button>
      </div>

      {/* Iteration history */}
      {history.length > 0 && (
        <div className="rounded-xl border border-border/40 bg-card p-5 shadow-sm">
          <h3 className="mb-3 text-[13px] font-semibold tracking-tight text-muted-foreground uppercase">
            Iteration History
          </h3>
          <div className="space-y-2">
            {history.map((entry) => (
              <div
                key={entry.version}
                className="flex items-center justify-between rounded-lg bg-muted/30 px-4 py-2.5"
              >
                <div className="flex items-center gap-2">
                  <span className="text-[13px] font-medium text-foreground">
                    v{entry.version}
                  </span>
                  <span className="text-[12px] text-muted-foreground">
                    {entry.items_applied.length} item{entry.items_applied.length !== 1 ? "s" : ""} applied
                  </span>
                  {entry.change_summary && (
                    <span className="text-[11px] text-muted-foreground/60 truncate max-w-[200px]" title={entry.change_summary}>
                      {entry.change_summary}
                    </span>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-1.5 text-[12px] tabular-nums">
                    <span className="text-muted-foreground">{entry.score_before}%</span>
                    <span className="text-muted-foreground/60">&rarr;</span>
                    <span className={entry.score_after !== null && entry.score_after > entry.score_before ? "text-green-600 font-medium" : entry.score_after !== null && entry.score_after < entry.score_before ? "text-red-500 font-medium" : "text-muted-foreground"}>
                      {entry.score_after !== null ? `${entry.score_after}%` : "..."}
                    </span>
                  </div>
                  {entry.snapshot && onRestore && !applyInProgress && (
                    <button
                      onClick={() => onRestore(entry)}
                      className="rounded p-1 text-muted-foreground/50 hover:bg-muted hover:text-muted-foreground transition-colors"
                      title={`Restore to v${entry.version}`}
                    >
                      <ClockCounterClockwise size={14} weight="bold" />
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* AI disclaimer */}
      <AIDisclaimer />
    </div>
  );
}
